[package]
name = "lowpass-filter"
version = "0.1.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-visualizer = "0.1.3" # to visualize the code + rerxport types

[dev-dependencies]
minimp3 = "0.5.1" # to test this filter